Update azure-pipelines-infrastructure.yml for Azure Pipelines

diff --git a/azure-pipelines-infrastructure.yml b/azure-pipelines-infrastructure.yml
--- a/azure-pipelines-infrastructure.yml
+++ b/azure-pipelines-infrastructure.yml
@@ -18,22 +18,41 @@ pool:
 stages:
 - stage: Deploy
   jobs:
-  - job: DeployNewCluster
+  - job: InstallAndCheckPrerequisites
     steps:
+    - task: KubectlInstaller@0
+      inputs:
+        kubectlVersion: 'latest'
+    - task: HelmInstaller@1
+      inputs:
+        helmVersionToInstall: 'latest'
+    - task: TerraformInstaller@0
+      inputs:
+        terraformVersion: '0.12.26'
     - task: Bash@3
-      displayName: 'Test variables'
+      displayName: 'Install prerequisites'
       inputs:
         targetType: 'inline'
         script: |
-          echo ${{ parameters.source_cluster }}
-          echo ${{ parameters.destination_cluster }}
-          echo $(testSecret)
-          ls
-          echo TEST
-
+          sudo apt install apache2-utils
+          wget https://github.com/heptio/velero/releases/download/v1.0.0/velero-v1.0.0-linux-amd64.tar.gz
+          tar zxvf velero-v1.0.0-linux-amd64.tar.gz
+          sudo mv velero-v1.0.0-linux-amd64/velero /usr/bin/
+          hash velero 2>/dev/null || { echo >&2 "I require velero but it's not installed. Aborting."; exit 1; }
+    - task: Bash@3
+      displayName: 'Check prerequisites'
+      inputs:
+        targetType: 'inline'
+        script: |
+          hash kubectl 2>/dev/null || { echo >&2 "I require kubectl but it's not installed. Aborting."; exit 1; }
+          hash az 2>/dev/null || { echo >&2 "I require az but it's not installed. Aborting."; exit 1; }
+          hash helm 2>/dev/null || { echo >&2 "I require helm but it's not installed. Aborting."; exit 1; }
+          hash velero 2>/dev/null || { echo >&2 "I require velero but it's not installed. Aborting."; exit 1; }
+          hash python 2>/dev/null || { echo >&2 "I require python but it's not installed. Aborting."; exit 1; }
+          hash htpasswd 2>/dev/null || { echo >&2 "I require htpasswd but it's not installed. Aborting."; exit 1; }
     - task: AzureCLI@2
       inputs:
-        azureSubscription: 'S941-Omnia-Radix-Development(16ede44b-1f74-40a5-b428-46cca9a5741b)'
+        azureSubscription: '$(azureSubscription)'
         scriptType: 'bash'
         scriptLocation: 'inlineScript'
         inlineScript: |
@@ -42,7 +61,7 @@ stages:
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
-                ls /home/vsts/work/1/s
+                RADIX_ZONE_ENV=./radix-zone/radix_zone_dev.env CLUSTER_NAME=marko-test-devops USER_PROMPT=false ./home/vsts/work/1/s/scripts/aks/bootstrap.sh
 
 #- task: Bash@3
 #  inputs:
