Update azure-pipelines-infrastructure.yml for Azure Pipelines

diff --git a/azure-pipelines-infrastructure.yml b/azure-pipelines-infrastructure.yml
--- a/azure-pipelines-infrastructure.yml
+++ b/azure-pipelines-infrastructure.yml
@@ -54,19 +54,44 @@ stages:
   jobs:
   - job: DeployNewCluster
     steps:
-    - task: AzureCLI@2
+    - task: KubectlInstaller@0
       inputs:
-        azureSubscription: 'ServiceConnectionAzureDevOpsRadixDev'
+        kubectlVersion: 'latest'
+    - task: HelmInstaller@1
+      inputs:
+        helmVersionToInstall: 'latest'
+    - task: TerraformInstaller@0
+      inputs:
+        terraformVersion: '0.12.26'
+    - task: Bash@3
+      displayName: 'Install prerequisites'
+      inputs:
+        targetType: 'inline'
+        script: |
+          sudo apt install apache2-utils
+          wget https://github.com/heptio/velero/releases/download/v1.0.0/velero-v1.0.0-linux-amd64.tar.gz
+          tar zxvf velero-v1.0.0-linux-amd64.tar.gz
+          sudo mv velero-v1.0.0-linux-amd64/velero /usr/bin/
+          hash velero 2>/dev/null || { echo >&2 "I require velero but it's not installed. Aborting."; exit 1; }
+    - task: Bash@3
+      displayName: 'Check prerequisites'
+      inputs:
+        targetType: 'inline'
+        script: |
+          hash kubectl 2>/dev/null || { echo >&2 "I require kubectl but it's not installed. Aborting."; exit 1; }
+          hash az 2>/dev/null || { echo >&2 "I require az but it's not installed. Aborting."; exit 1; }
+          hash helm 2>/dev/null || { echo >&2 "I require helm but it's not installed. Aborting."; exit 1; }
+          hash velero 2>/dev/null || { echo >&2 "I require velero but it's not installed. Aborting."; exit 1; }
+          hash python 2>/dev/null || { echo >&2 "I require python but it's not installed. Aborting."; exit 1; }
+          hash htpasswd 2>/dev/null || { echo >&2 "I require htpasswd but it's not installed. Aborting."; exit 1; }
+
+    - task: AzureCLI@2
+      displayName: 'AzureCLI - Migrate Cluster'
+      inputs:
+        azureSubscription: '$(azureSubscription)'
         scriptType: 'bash'
-        scriptLocation: 'inlineScript'
-        inlineScript: |
-          echo --------------1----------------
-          ls
-          echo --------------2----------------
-          cd scripts
-          echo --------------3----------------
-          ls
-          echo --------------4----------------
+        scriptLocation: 'scriptPath'
+        scriptPath: 'scripts/migrate.sh'
       env:
         SOURCE_CLUSTER: ${{ parameters.source_cluster }}
         DEST_CLUSTER: ${{ parameters.destination_cluster }}
@@ -74,6 +99,7 @@ stages:
         MOVE_INGRESSES: ${{ parameters.move_ingresses }}
         PIPELINE_RUN: ${{ parameters.pipeline_run }}
         SPOID: $(SPOID)
+
 #- task: Bash@3
 #  inputs:
 #    targetType: 'inline'
